name: milk_tea
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/banner/
    - assets/images/trasua/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-Bold.ttf  
        - asset: assets/fonts/Nunito-ExtraBold.ttf  
        - asset: assets/fonts/Nunito-Black.ttf  
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf